### ISSUE TITLE
Dask workers restarting results in ValueError on intermediate files

### ISSUE THREAD

**Issue by stargaser** [astronomy-commons/hipscat-import#116]
I'm trying to run the AllWISE example import. After an initial completion of Planning:
```
Planning : 100%|█████████████████████████████████| 5/5 [00:00<00:00, 615.24it/s]
```
I get a never-ending string of errors like this:
```
2023-08-09 12:31:14,359 - distributed.nanny - WARNING - Restarting worker
Planning :   0%|                                          | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/stage/irsa-staff-shupe/micromamba/envs/hipscat/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/stage/irsa-staff-shupe/micromamba/envs/hipscat/lib/python3.11/multiprocessing/spawn.py", line 129, in _main
    prepare(preparation_data)
  File "/stage/irsa-staff-shupe/micromamba/envs/hipscat/lib/python3.11/multiprocessing/spawn.py", line 240, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/stage/irsa-staff-shupe/micromamba/envs/hipscat/lib/python3.11/multiprocessing/spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/stage/irsa-staff-shupe/hipscat/allwise/runimport.py", line 11, in <module>
    args = ImportArguments(
           ^^^^^^^^^^^^^^^^
  File "<string>", line 33, in __init__
  File "/stage/irsa-staff-shupe/micromamba/envs/hipscat/lib/python3.11/site-packages/hipscat_import/catalog/arguments.py", line 78, in __post_init__
    self._check_arguments()
  File "/stage/irsa-staff-shupe/micromamba/envs/hipscat/lib/python3.11/site-packages/hipscat_import/catalog/arguments.py", line 123, in _check_arguments
    self.resume_plan = ResumePlan(
                       ^^^^^^^^^^^
  File "<string>", line 9, in __init__
  File "/stage/irsa-staff-shupe/micromamba/envs/hipscat/lib/python3.11/site-packages/hipscat_import/catalog/resume_plan.py", line 51, in __post_init__
    self.gather_plan()
  File "/stage/irsa-staff-shupe/micromamba/envs/hipscat/lib/python3.11/site-packages/hipscat_import/catalog/resume_plan.py", line 61, in gather_plan
    raise ValueError(
ValueError: tmp_path (/stage/irsa-staff-shupe/hipscat/allwise/tmp/allwise2/intermediate) contains intermediate files. choose a different directory or use --resume flag
```

**Comment by delucchi-cmu** [comment]
This is behavior that we'll change for v0.2. For now, please use the `resume` flag when initializing your pipeline. e.g. 

```
args = ImportArguments(
    ...
    resume=True,
    overwrite=True,
)
runner.pipeline(args)
```

**Comment by stargaser** [comment]
I tried `overwrite=True` and `resume=True`. I get two runs of Planning, followed by a warning that maybe a cluster is running already, followed by an error.

```
Planning : 100%|████████████████████████████████| 5/5 [00:00<00:00, 1067.80it/s]
Planning : 100%|████████████████████████████████| 5/5 [00:00<00:00, 1699.47it/s]
/stage/irsa-staff-shupe/hipscat/allwise/venv/lib/python3.11/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 41397 instead
  warnings.warn(
2023-08-15 13:52:26,916 - distributed.nanny - ERROR - Failed to start process
Traceback (most recent call last):
  File "/stage/irsa-staff-shupe/hipscat/allwise/venv/lib/python3.11/site-packages/distributed/nanny.py", line 434, in instantiate
    result = await self.process.start()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/stage/irsa-staff-shupe/hipscat/allwise/venv/lib/python3.11/site-packages/distributed/nanny.py", line 722, in start
    await self.process.start()
  File "/stage/irsa-staff-shupe/hipscat/allwise/venv/lib/python3.11/site-packages/distributed/process.py", line 55, in _call_and_set_future
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/stage/irsa-staff-shupe/hipscat/allwise/venv/lib/python3.11/site-packages/distributed/process.py", line 215, in _start
    process.start()
  File "/stage/irsa-staff-shupe/micromamba/envs/hipscat/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/stage/irsa-staff-shupe/micromamba/envs/hipscat/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/stage/irsa-staff-shupe/micromamba/envs/hipscat/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/stage/irsa-staff-shupe/micromamba/envs/hipscat/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/stage/irsa-staff-shupe/micromamba/envs/hipscat/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/stage/irsa-staff-shupe/micromamba/envs/hipscat/lib/python3.11/multiprocessing/spawn.py", line 158, in get_preparation_data
    _check_not_importing_main()
  File "/stage/irsa-staff-shupe/micromamba/envs/hipscat/lib/python3.11/multiprocessing/spawn.py", line 138, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by delucchi-cmu** [comment]
Are you using a main guard to run the pipeline? e.g. 

```
import stuff

def main():
    args = ImportArguments(
      ...
    )
    runner.pipeline(args)

if __name__ == '__main__':
    main()
```

If this doesn't improve things, can you add the code you're using to start the pipeline?

**Comment by stargaser** [comment]
Using a main guard works when using `resume=True` and `overwrite=True`. Thanks for the tip! Would it be worth it to add to the docs in the example scripts, or (easier) in Debugging Tips?
